name: Daily Gold Price Update

on:
  schedule:
    - cron: "0 21 * * 1-5"  # Runs at 4 PM ET (21:00 UTC) Mon-Fri
  workflow_dispatch:  # Allow manual runs

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Fetch latest gold price
        run: python scripts/fetch_data.py
      
      - name: Retrain model
        run: python scripts/train_model.py
      
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/gold_prices.csv models/gold_price_model.pkl
          git commit -m "Auto-update: New data and model"
          git push